### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'defaultGraph')

### ISSUE THREAD

**Issue by mielvds** [rubensworks/rdf-data-factory.js#19]
I'm creating a simple dataset like so:

    import type { Quad } from "@rdfjs/types"
    import { DataFactory } from "rdf-data-factory"; 
    import { isomorphic } from "rdf-isomorphic";

    const {quad, namedNode, literal, blankNode} = new DataFactory();

    const subject = namedNode("http://example.org/subject1")
    const subject2 = namedNode("http://example.org/subject2")
    const urn = namedNode("urn:test:b1")

    const triples = [
        quad(subject, namedNode("https://github.com/dbcls/grasp/ns/iri"), subject),
        quad(subject, namedNode("https://github.com/dbcls/grasp/ns/id"), literal("subject1")),
        quad(subject, namedNode("https://github.com/dbcls/grasp/ns/count"), literal("5", namedNode('http://www.w3.org/2001/XMLSchema#int'))),
        quad(subject, namedNode("https://github.com/dbcls/grasp/ns/test"), literal("true", namedNode('http://www.w3.org/2001/XMLSchema#boolean'))),
        quad(subject, namedNode("https://github.com/dbcls/grasp/ns/obsolete"), literal("obsolete")),
        quad(subject2, namedNode("https://github.com/dbcls/grasp/ns/iri"), subject2),
        quad(subject2, namedNode("https://github.com/dbcls/grasp/ns/id"), literal("subject2")),
        quad(subject2, namedNode("https://github.com/dbcls/grasp/ns/count"), literal("4", namedNode('http://www.w3.org/2001/XMLSchema#int'))),
        quad(subject2, namedNode("https://github.com/dbcls/grasp/ns/test"), literal("false", namedNode('http://www.w3.org/2001/XMLSchema#boolean'))),
        quad(urn, namedNode("https://github.com/dbcls/grasp/ns/iri"), subject),
        quad(urn, namedNode("https://github.com/dbcls/grasp/ns/id"), literal("subject")),
    ]

But I get the following error on `quad`: `TypeError: Cannot read properties of undefined (reading 'defaultGraph')` Any idea what's causing this?

**Comment by mielvds** [comment]
Okay, the deconstruction `const {quad, namedNode, literal, blankNode} = new DataFactory();
` doesn't work, it needs to be `factory.quad` and so on.

**Comment by rubensworks** [comment]
Indeed, those are methods on the `DataFactory` object, so they need to be invoked on the object instance.

You could probably use something like `bind()` if you don't want to repeat the factory instance.

(FYI, I usually use https://github.com/rubensworks/rdf-quad.js when manually creating quads, to make things less verbose)

**Comment by mielvds** [comment]
Thanks @rubensworks . I actually just switched from  rdf-quad for no particular reason other than it works a little better with typescript :)
