### ISSUE TITLE
`Quad.equals` is not lenient with non-RDF* quads

### ISSUE THREAD

**Issue by larsrh** [rubensworks/rdf-data-factory.js#2]
This check is slightly too aggressive:

https://github.com/rubensworks/rdf-data-factory.js/blob/eded3533af4f1f068625cfdc7e2c31de2cffb46f/lib/Quad.ts#L28

It could be made more lenient, like so:

https://github.com/rdfjs-base/data-model/blob/ed59e75132ee4d8a3a2f58443ff6a4f792a97033/lib/quad.js#L16-L17

**Comment by rubensworks** [comment]
Good point, I forgot about this. Added in 1.0.2.

**Comment by larsrh** [comment]
Excellent, thanks!
