### ISSUE TITLE
Feature request: Add support for namespaces

### ISSUE THREAD

**Issue by kelvinhammond** [rubensworks/rdf-data-factory.js#20]
Hello,

I think there should be support for namespaces with some common namespaces included such as `XSD`, `RDF`, `RDFS`, etc.

Example namespace libraries:
- https://github.com/rdfjs-base/namespace
- https://github.com/rdf-ext/rdf-ext
- https://github.com/ontola/ontologies#ontologiescore

**Comment by rubensworks** [comment]
This is not in scope of this project.
This library is just meant to be a lightweight datafactory implementation.
But namespace libs could certainly be built on top of this.
