### ISSUE TITLE
Is `@types/rdf-js` still needed as a dependency?

### ISSUE THREAD

**Issue by pmcb55** [rubensworks/rdf-data-factory.js#4]
The `package.json` still has a dependency on `@types/rdf-js`, i.e.,:
```json
:
  "dependencies": {
    "@types/rdf-js": "*"
  },
:
```
...but when I `npm install` from my library that depends on `rdf-data-factory`, I get the following warning telling me that it's no longer necessary:
```
npm WARN deprecated @types/rdf-js@4.0.2: This is a stub types definition. rdf-js provides its own type definitions, so you do not need this installed.
```
Can this dependency just be removed to tidy up this warning from dependent libraries...?

**Comment by rubensworks** [comment]
It actually needs to be migrated to `@rdfjs/types`. It's something I have to do across all my repos, so it will require quite a bit of work. I hope to do it soon though.
